version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew lint test
